export const INITIATE_SEARCH_SONGS = "INITIATE_SEARCH_SONGS";
export const GET_SEARCHED_SONGS_SUCCESS = "GET_SEARCHED_SONGS_SUCCESS";
export const GET_SEARCHED_SONGS_ERROR = "GET_SEARCHED_SONGS_ERROR";