export const INITIATE_VERIFY_OTP = "INITIATE_VERIFY";
export const RESET_VERIFY_OTP = "RESET_VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";