const QUERY_KEYS = {
  LOGIN_USER: "LOGIN_USER",
  MOST_POPULAR_SONGS: "MOST_POPULAR_SONGS",
  FILTERED_SONGS: "FILTERED_SONGS",
  FILTERED_SONGS_INFINITE_QUERY: "FILTERED_SONGS_INFINITE_QUERY",
};

export default QUERY_KEYS;
