const QUERY_KEYS = {
  LOGIN_USER: "LOGIN_USER",
  MOST_POPULAR_SONGS: "MOST_POPULAR_SONGS",
  FILTERED_SONGS: "FILTERED_SONGS",
  FILTERED_SONGS_INFINITE_QUERY: "FILTERED_SONGS_INFINITE_QUERY",
  RECENT_SONGS_INFINITE_QUERY: "RECENT_SONGS_INFINITE_QUERY",
  ALBUMS_INFINITE_QUERY: "ALBUMS_INFINITE_QUERY",
  ARTISTS_INFINITE_QUERY: "ARTISTS_INFINITE_QUERY",
  GET_ALBUM_DETAIL: "GET_ALBUM_DETAIL",
  GET_ALBUM_SONGS_INFINITE_QUERY: "GET_ALBUM_SONGS_INFINITE_QUERY",
  GET_ARTIST_DETAIL: "GET_ARTIST_DETAIL",
  GET_ARTIST_SONGS_INFINITE_QUERY: "GET_ARTIST_SONGS_INFINITE_QUERY",
  FILTERED_PLAYLISTS_INFINITE_QUERY: "FILTERED_PLAYLISTS_INFINITE_QUERY",
  GET_PLAYLIST_SONGS_INFINITE_QUERY: "GET_PLAYLIST_SONGS_INFINITE_QUERY",
  REACT_ON_A_SONG: "REACT_ON_A_SONG",
  NEUTRALIZE_REACTION_ON_A_SONG: "NEUTRALIZE_REACTION_ON_A_SONG",
  GET_RANDOM_SONG: "GET_RANDOM_SONG",
};

export default QUERY_KEYS;
