const QUERY_KEYS = {
  LOGIN_USER: "LOGIN_USER",
  MOST_POPULAR_SONGS: "MOST_POPULAR_SONGS",
  FILTERED_SONGS: "FILTERED_SONGS",
  FILTERED_SONGS_INFINITE_QUERY: "FILTERED_SONGS_INFINITE_QUERY",
  RECENT_SONGS_INFINITE_QUERY: "RECENT_SONGS_INFINITE_QUERY",
  ALBUMS_INFINITE_QUERY: "ALBUMS_INFINITE_QUERY",
  ARTISTS_INFINITE_QUERY: "ARTISTS_INFINITE_QUERY",
  GET_ALBUM_DETAIL: "GET_ALBUM_DETAIL",
  GET_ALBUM_SONGS_INFINITE_QUERY: "GET_ALBUM_SONGS_INFINITE_QUERY",
  GET_ARTIST_DETAIL: "GET_ARTIST_DETAIL",
  GET_ARTIST_SONGS_INFINITE_QUERY: "GET_ARTIST_SONGS_INFINITE_QUERY",
  FILTERED_PLAYLISTS_INFINITE_QUERY: "FILTERED_PLAYLISTS_INFINITE_QUERY",
  GET_PLAYLIST_SONGS_INFINITE_QUERY: "GET_PLAYLIST_SONGS_INFINITE_QUERY",
};

export const INIFINITE_SONGS_QUERY_KEYS = {
  FILTERED_SONGS_INFINITE_QUERY: QUERY_KEYS.FILTERED_SONGS_INFINITE_QUERY,
  RECENT_SONGS_INFINITE_QUERY: QUERY_KEYS.RECENT_SONGS_INFINITE_QUERY,
  GET_ALBUM_SONGS_INFINITE_QUERY: QUERY_KEYS.GET_ALBUM_SONGS_INFINITE_QUERY,
  GET_ARTIST_SONGS_INFINITE_QUERY: QUERY_KEYS.GET_ARTIST_SONGS_INFINITE_QUERY,
  GET_PLAYLIST_SONGS_INFINITE_QUERY:
    QUERY_KEYS.GET_PLAYLIST_SONGS_INFINITE_QUERY,
};

export type DATA_SHARING_FOR_PLAYLIST_TYPE =
  keyof typeof INIFINITE_SONGS_QUERY_KEYS;

export default QUERY_KEYS;
