export const TRIOLOGY_ID = "TRIOLOGY_ID";
export const SIDEBAR_CONTAINER_ID = "SIDEBAR_CONTAINER_ID";
export const SIDEBAR_OPENER_ID = "SIDEBAR_OPENER_ID";
export const OPTION_SELECTOR_OPENER = "OPTION_SELECTOR_OPENER";
