export const INITIATE_LOGIN = "INITIATE_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGOUT = "LOGOUT"

export const INITIATE_UPLOAD = "INITIATE_UPLOAD" 
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS" 
export const UPLOAD_FAILURE = "UPLOAD_FAILURE" 

export const INITIATE_ADD_ALBUM = "INITIATE_ADD_ALBUM"
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS"
export const ADD_ALBUM_FAILURE = "ADD_ALBUM_FAILURE"
export const RESET_ADD_ALBUM = "RESET_ADD_ALBUM"
