// Create Playlist
export const INITIATE_CREATE_PLAYLIST = "INITIATE_CREATE_PLAYLIST";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";

// Delete Playlist
export const INITIATE_DELETE_PLAYLIST = "INITIATE_DELETE_PLAYLIST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_ERROR = "DELETE_PLAYLIST_ERROR";

// Get liked songs
export const INITIATE_LIKED_SONGS = "INITIATE_LIKED_SONGS";
export const GET_LIKED_SONGS_SUCCESS = "GET_LIKED_SONGS_SUCCESS";
export const GET_LIKED_SONGS_ERROR = "GET_LIKED_SONGS_ERROR";

// Login
export const INITIATE_LOGIN = "INITIATE_LOGIN";
export const INITIATE_LOGIN_WITH_TOKEN = "INITIATE_LOGIN_WITH_TOKEN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

// Get most viewed songs
export const INITIATE_GET_MOST_VIEWED_SONGS = "INITIATE_GET_MOST_VIEWED_SONGS";
export const GET_MOST_VIEWED_SONGS_SUCCESS = "GET_MOST_VIEWED_SONGS_SUCCESS";
export const GET_MOST_VIEWED_SONGS_ERROR = "GET_MOST_VIEWED_SONGS_ERROR";

// Set Music Player Song Id
export const SET_SONG_ID = "SET_SONG_ID";
export const SET_SONG_INDEX = "SET_SONG_INDEX";
export const SET_NEXT_INDEX = "SET_NEXT_INDEX";
export const SET_PREV_INDEX = "SET_PREV_INDEX";
export const SET_SONG = "SET_SONG";

// Recent Songs
export const INITIATE_RECENT_SONGS = "INITIATE_RECENT_SONGS";
export const GET_RECENT_SONGS_SUCCESS = "GET_RECENT_SONGS_SUCCESS";
export const GET_RECENT_SONGS_ERROR = "GET_RECENT_SONGS_ERROR";

// Registration
export const INITIATE_REGISTRATION = "INITIATE_REGISTRATION"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILED = "REGISTRATION_FAILED"
export const REGISTRATION_STATE_RESET = "REGISTRATION_STATE_RESET"

// Search songs
export const INITIATE_SEARCH_SONGS = "INITIATE_SEARCH_SONGS";
export const GET_SEARCHED_SONGS_SUCCESS = "GET_SEARCHED_SONGS_SUCCESS";
export const GET_SEARCHED_SONGS_ERROR = "GET_SEARCHED_SONGS_ERROR";

// Verify OTP
export const INITIATE_VERIFY_OTP = "INITIATE_VERIFY";
export const RESET_VERIFY_OTP = "RESET_VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED";

// Music Player Playlist
export const SHOW_PLAYLIST = "SHOW_PLAYLIST";
export const HIDE_PLAYLIST = "HIDE_PLAYLIST";
export const TOGGLE_PLAYLIST = "TOGGLE_PLAYLIST";