export const INITIATE_LOGIN = "INITIATE_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGOUT = "LOGOUT"

export const INITIATE_UPLOAD = "INITIATE_UPLOAD" 
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS" 
export const UPLOAD_FAILURE = "UPLOAD_FAILURE" 

export const INITIATE_ADD_ALBUM = "INITIATE_ADD_ALBUM"
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS"
export const ADD_ALBUM_FAILURE = "ADD_ALBUM_FAILURE"
export const RESET_ADD_ALBUM = "RESET_ADD_ALBUM"

export const INITIATE_ADD_ARTIST = "INITIATE_ADD_ARTIST"
export const ADD_ARTIST_SUCCESS = "ADD_ARTIST_SUCCESS"
export const ADD_ARTIST_FAILURE = "ADD_ARTIST_FAILURE"
export const RESET_ADD_ARTIST = "RESET_ADD_ARTIST"

export const INITIATE_SEARCH_ALBUM = "INITIATE_SEARCH_ALBUM"
export const SEARCH_ALBUM_SUCCESS = "SEARCH_ALBUM_SUCCESS"
export const SEARCH_ALBUM_FAILURE = "SEARCH_ALBUM_FAILURE"
export const RESET_SEARCH_ALBUM = "RESET_SEARCH_ALBUM"

export const INITIATE_SEARCH_ARTIST = "INITIATE_SEARCH_ARTIST"
export const SEARCH_ARTIST_SUCCESS = "SEARCH_ARTIST_SUCCESS"
export const SEARCH_ARTIST_FAILURE = "SEARCH_ARTIST_FAILURE"
export const RESET_SEARCH_ARTIST = "RESET_SEARCH_ARTIST"

export const INITIATE_SEARCH_GENRE = "INITIATE_SEARCH_GENRE"
export const SEARCH_GENRE_SUCCESS = "SEARCH_GENRE_SUCCESS"
export const SEARCH_GENRE_FAILURE = "SEARCH_GENRE_FAILURE"
export const RESET_SEARCH_GENRE = "RESET_SEARCH_GENRE"