export const INITIATE_GET_MOST_VIEWED_SONGS = "INITIATE_GET_MOST_VIEWED_SONGS";
export const GET_MOST_VIEWED_SONGS_SUCCESS = "GET_MOST_VIEWED_SONGS_SUCCESS";
export const GET_MOST_VIEWED_SONGS_ERROR = "GET_MOST_VIEWED_SONGS_ERROR";