export const INITIATE_REGISTRATION = "INITIATE_REGISTRATION"
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAILED = "REGISTRATION_FAILED"
export const REGISTRATION_STATE_RESET = "REGISTRATION_STATE_RESET"